.gitignore

Added .DS_Store to gitignore file so that it doesn't cause problems in the future.

Added .DS_Store to gitignore file

---

src/app.py

Created basic app skeleton with slider. Please test that the app runs on your computers. Feel free to add/modify whatever you think complements the project.

Created simple app.py skeleton

---

environment.yml

Created environment file with necessary dependencies to work on Dash.

Created provisional environment file

---

reports/proposal.md

please let me know if you guys have any comments!

m1 section 3

---

CONTRIBUTING.md
README.md
reports/m1_proposal.md

Edits for proposal, contributing and readme included here. Ready for review!

Doc edits - proposal, contributing, readme

---

src/app.py

Here is the structure of the app. We have to update the environment to use it.

App layout

---

CONTRIBUTING.md
README.md

- readme just needs the GIF demo, other than that its ready
- contributing was updated to add the command to run app.py

Milestone 2 updates to Readme

---

README.md

Added data source for the panel_data file.

add data source

---

data/raw/panels.csv

source: https://volts.ca/collections/solar-panels

panel_data

---

README.md

name update

---

environment.yml
src/app.py

Layout modifications

---

src/app.py

Layout modified and colored title

---

src/app.py
src/callbacks.py
src/components.py
src/data.py

Hi Team! I modularized the app. Please review it so that we can work on it from there.

Code modularized

---

src/callbacks.py
src/components.py
src/data.py

I only touched the code that involved using make up data- but the region is not selectable, not really sure what the issue is.

incorporate real data

---

src/components.py

Coordinates for BC to Manitoba added

added province zoom coordinates

---

src/app.py

Just an update for dropdown string display

name uppdate

---

src/app.py
src/callbacks.py
src/components.py

Added the sidebar and bottom panel comparison bar. Some minor formatting is still needed for next week :)

Dashboard Formatting

---

reports/m3-reflection.md

complete reflection for m3

---

src/callbacks.py

Added caching feature to default chart plotting functions

Added caching to default graph functions

---

src/callbacks.py
src/components.py

Fixed issue with card format not being stable after updating values.

Card updating

---

src/app.py
src/components.py

added "Solar Savers" to the tab title and formatted the button on the header.

Tab title & button

---

src/app.py
src/callbacks.py
src/components.py

Enlarged the map and added padding for better alignment

Map alignment

---

src/callbacks.py
src/components.py

Fixed the slider so the 20 is no longer displayed in the middle upon new max. Note: the max is not displayed at the end tick. If you know how to fix it feel free to add it in before merging.

Left panel - slider 

---

src/components.py

github link and updated date is in app description on the dashboard

added link github and updated date
